import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { BudgetProvider } from "@/components/BudgetContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Link href="/">Home</Link>
        <Link href="/about">About</Link> */}
        <BudgetProvider>{children}</BudgetProvider>
      </body>
    </html>
  );
}
